[programs.devnet]
myepicproject = "HAii6Cj6oiXgiJNwTU1dE4Xyair7edJVm2frG9qxTVPF"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/kevinkabore/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js" 
