const anchor = require('@project-serum/anchor')

// Need the system program
const {SystemProgram} = anchor.web3

const main = async () => {
  console.log('--------------------')
  console.log('🚀 Starting tests...')
  console.log('⏳ 1. It initializes the program with 0 total_gifs')

  // set chain provider to use data generated by solana config get (local env in this case)
  const provider = anchor.Provider.env()
  anchor.setProvider(provider)

  // anchor automatically compiles the program in lib.rs
  const {Myepicproject: MyEpicProjectProgram} = anchor.workspace // Anchor knows to look at programs/myepicproject/src/lib.rs b/c we used anchor.workspace.Myepicproject.

  // create some credentials (keypair) for our BaseAccount we;re creating.
  const baseAccount = anchor.web3.Keypair.generate()

  // call start_stuff_off, pass it the params we defined i `pub struct StartStuffOff`
  let tx = await MyEpicProjectProgram.rpc.startStuffOff({
    // function start_stuff_off is camelCase in JS thanks to Anchor 🤝
    accounts: {
      baseAccount: baseAccount.publicKey,
      user: provider.wallet.publicKey,
      systemProgram: SystemProgram.programId,
    },
    signers: [baseAccount],
  })
  console.log('🧾 Your transaction signature: ', tx)

  // Fetch data from the program account.
  let programAccount = await MyEpicProjectProgram.account.baseAccount.fetch(
    baseAccount.publicKey,
  )
  console.log('🧾 Program Account: ', programAccount)
  let totalGifs = programAccount.totalGifs.toString()
  console.log('👀 Total gifs:', totalGifs)
  if (parseInt(totalGifs) === 0) {
    console.log('✅ Test passed! 🎉')
    console.log('--------------------')
  } else {
    console.log('❌ Test failed! 💥')
    console.log('--------------------')
  }

  console.log('⏳ 2. It adds a gif')
  console.log('🧾 Program Account Before adding a gif: ', programAccount)
  let gifUrl =
    'https://media0.giphy.com/media/NEvPzZ8bd1V4Y/giphy.gif?cid=bb5a1c3afqsy5s4e2yf64q8thitrdyce66uoqy93r1c3vqbp&rid=giphy.gif&ct=g'
  await MyEpicProjectProgram.rpc.addGif(gifUrl, {
    // AddGif context only accepts baseAccount
    accounts: {
      baseAccount: baseAccount.publicKey,
    },
  })

  programAccount = await MyEpicProjectProgram.account.baseAccount.fetch(
    baseAccount.publicKey,
  )
  totalGifs = programAccount.totalGifs.toString()
  console.log('👀 Total gifs:', totalGifs)
  let gifList = programAccount.gifList
  console.log('👀 GIF List', gifList)
  console.log('gifList len:', gifList.length)

  console.log('🧾 Program Account After adding a gif: ', programAccount)

  if (parseInt(totalGifs) === 1) {
    console.log('✅ Test passed! 🎉')
    console.log('--------------------')
  } else {
    console.log('❌ Test failed! 💥')
    console.log('--------------------')
  }
}

// Just to run our main function asynchrosly
const runMain = async () => {
  try {
    await main()
    process.exit(0)
  } catch (e) {
    console.error(e)
    process.exit(1)
  }
}

runMain()
